Integrated offline map updater
heremaps/here-sdk-ref-app-flutter pull request #22
Opened 2021-11-15 10:25 UTC by Merlin1stHere

Signed-off-by: Vitalii Khoruzhyi <44439675+Merlin1stHere@users.noreply.github.com>

2021-11-15 11:01 UTC, stefan-troyke approved these changes

2021-11-15 12:40 UTC, ephmoc approved these changes

2021-11-15 12:45 UTC, ppiatkowski-here requested changes

2021-11-17 07:49 UTC, Merlin1stHere commented on lib/download_maps/map_loader_controller.dart
> +  }
Fixed

2021-11-17 09:27 UTC, ppiatkowski-here approved these changes

2021-11-17 09:28 UTC, merged