Fix for app freeze on restore while navigation is in progress
heremaps/here-sdk-ref-app-flutter pull request #62
Opened 2022-09-05 12:53 UTC by tstaszak89

FlutterEngine is cached and reused if MainActivity is killed (on
Android). Notification service is stopped when application view is
killed.

2022-09-05 13:15 UTC, stefan-troyke approved these changes

2022-09-06 09:55 UTC, stefan-troyke requested changes
Ok, tested and build the app myself. Unfortunately, the result is not necessary better.

2022-11-10 15:48 UTC, ppiatkowski-here approved these changes

2022-11-25 13:47 UTC, stefan-troyke approved these changes

2022-11-25 13:49 UTC, merged