Consent status not gets updated on acceptance just after fresh install
heremaps/here-sdk-ref-app-flutter pull request #69
Opened 2023-01-05 12:39 UTC by mohan-manthri

Cause:
- UI is not getting updated after user accepting the consent.

Fix:
- Wait for the user consent and then update UI.

Signed-off-by: manthri <119850631+mohan-manthri@users.noreply.github.com>

2023-01-05 14:02 UTC, stefan-troyke approved these changes

2023-01-05 14:12 UTC, ppiatkowski-here approved these changes

2023-01-05 14:15 UTC, ppiatkowski-here requested changes

2023-01-05 14:15 UTC, ppiatkowski-here commented on lib/landing_screen.dart
> +        setState(() {});
I'm not a fan of empty setState() methods. UI should be determined by state. If we need to force update of UI without changing the state then UI is not determined by state.

2023-01-06 06:05 UTC, mohan-manthri commented on lib/landing_screen.dart
> +        setState(() {});
Done, Modified as suggested.

2023-01-07 01:28 UTC, Guru-cm-here approved these changes

2023-01-09 08:56 UTC, ppiatkowski-here approved these changes

2023-01-09 09:59 UTC, tstaszak89 approved these changes

2023-01-09 10:13 UTC, merged