Implemented offline map loading feature
heremaps/here-sdk-ref-app-flutter pull request #9
Opened 2021-09-24 10:13 UTC by Merlin1stHere

Signed-off-by: Vitalii Khoruzhyi <44439675+Merlin1stHere@users.noreply.github.com>

2021-09-24 15:11 UTC, ephmoc requested changes

2021-09-24 15:11 UTC, ephmoc commented on lib/download_maps/storage_space_widget.dart
> +      _totalSpace = (totalDiskSpace * 1048576).toInt();
Why not in setState?

2021-09-24 15:11 UTC, ephmoc commented on lib/download_maps/storage_space_widget.dart
> +      _availableSpace = (freeDiskSpace * 1048576).toInt();
Why not in setState?

2021-09-27 06:16 UTC, Merlin1stHere commented on lib/download_maps/storage_space_widget.dart
> +      _availableSpace = (freeDiskSpace * 1048576).toInt();
fixed

2021-09-27 13:16 UTC, ephmoc approved these changes

2021-09-27 13:19 UTC, merged